#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/Xresources
usermodmap="$XDG_CONFIG_HOME"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
USERXSESSION="$XDG_CACHE_HOME"/X11/xsession
USERXSESSIONRC="$XDG_CACHE_HOME"/X11/xsessionrc
ALTUSERXSESSION="$XDG_CACHE_HOME"/X11/Xsession
ERRFILE="$XDG_CACHE_HOME"/X11/xsession-errors

# merge in defaults and keymaps
if [ -f $sysresources ]; then
        xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
        xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
        xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
        xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi

# for firefox
export MOZ_X11_EGL=1

# fix clipboard
while :; do
    pgrep -f "xclip.*clip" || xclip -sel clip -o | xclip -sel clip
    sleep 1
done &

# keep this at the bottom
session=${1:-xmonad}

case $session in
xmonad)
	export XDG_CURRENT_DESKTOP=xmonad
	export XDG_SESSION_TYPE=x11
        dbus-run-session ~/.local/share/xmonad/xmonad-x86_64-linux
        ;;
dwm)
	export XDG_CURRENT_DESKTOP=dwm
	export XDG_SESSION_TYPE=x11
        dbus-run-session dwm
        ;;
kde)
        dbus-run-session startplasma-x11
        ;;
xfce | xfce4)
        dbus-run-session startxfce4
        ;;
gnome)
        dbus-run-session gnome-session
        ;;
frankenWM | franken)
        dbus-run-session frankenwm
        ;;
spectrwm | spectr)
        dbus-run-session spectrwm
        ;;
awesome)
        dbus-run-session awesome
        ;;
*)
        dbus-run-session "$1"
        ;;
esac
