#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/Xresources
usermodmap="$XDG_CONFIG_HOME"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
USERXSESSION="$XDG_CACHE_HOME"/X11/xsession
USERXSESSIONRC="$XDG_CACHE_HOME"/X11/xsessionrc
ALTUSERXSESSION="$XDG_CACHE_HOME"/X11/Xsession
ERRFILE="$XDG_CACHE_HOME"/X11/xsession-errors

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

# keep this at the bottom
session=${1:-xmonad}

case $session in
    xmonad		) exec xmonad;;
    dwm 		) exec dwm;;
    kde		      	) exec startplasma-x11;;
    xfce|xfce4		) exec startxfce4;;
    gnome		) exec gnome-session;;
    *			) exec "$1";;
esac
