#!/bin/sh

userresources="$XDG_CONFIG_HOME"/x11/Xresources

# merge in defaults and keymaps
[ -f "$userresources" ] && xrdb -merge "$userresources"

# for firefox
export MOZ_X11_EGL=1
export XDG_SESSION_TYPE=x11

# keyring
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# fix clipboard
#while :; do
#        pgrep -f "xclip.*clip" || xclip -sel clip -o | xclip -sel clip
#        sleep 1
#done &

# keep this at the bottom
session=${1:-xmonad}
export XDG_SESSION_DESKTOP=$session
export XDG_CURRENT_DESKTOP=$session

case $session in
        xmonad)
                exec ~/.local/share/xmonad/xmonad-x86_64-linux
                ;;
        dwm)
                exec dwm
                ;;
        kde)
                exec startplasma-x11
                ;;
        xfce | xfce4)
                exec startxfce4
                ;;
        gnome)
                exec gnome-session
                ;;
        spectrwm | spectr)
                exec spectrwm
                ;;
        awesome)
                exec awesome
                ;;
        *)
                $1
                ;;
esac
