#!/bin/sh

userresources="$XDG_CONFIG_HOME"/x11/Xresources
usermodmap="$XDG_CONFIG_HOME"/x11/Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap
USERXSESSION="$XDG_CACHE_HOME"/x11/xsession
USERXSESSIONRC="$XDG_CACHE_HOME"/x11/xsessionrc
ALTUSERXSESSION="$XDG_CACHE_HOME"/x11/Xsession
ERRFILE="$XDG_CACHE_HOME"/x11/xsession-errors

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
                [ -x "$f" ] && . "$f"
        done
        unset f
fi

# for firefox
export MOZ_X11_EGL=1
export XDG_SESSION_TYPE=x11

# fix clipboard
#while :; do
#        pgrep -f "xclip.*clip" || xclip -sel clip -o | xclip -sel clip
#        sleep 1
#done &

# keep this at the bottom
session=${1:-xmonad}
export XDG_SESSION_DESKTOP=$session
export XDG_CURRENT_DESKTOP=$session

case $session in
        xmonad)
                exec ~/.local/share/xmonad/xmonad-x86_64-linux
                ;;
        dwm)
                exec dwm
                ;;
        kde)
                exec startplasma-x11
                ;;
        xfce | xfce4)
                exec startxfce4
                ;;
        gnome)
                exec gnome-session
                ;;
        spectrwm | spectr)
                exec spectrwm
                ;;
        awesome)
                exec awesome
                ;;
        *)
                $1
                ;;
esac
