[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-onedark
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-onedark
GtkTheme=oomox-onedark
IconTheme=oomox-onedark
MetacityTheme=oomox-onedark
